### ISSUE TITLE
Explorer reporting different balance to wallet

### ISSUE THREAD

**Issue by norbsy** [bulwark-crypto/bulwark-explorer#148]
## Steps to Reproduce the Problem

  1. Explorer shows a certain balance
  2. In wallet balance for that address is different
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by sotblad** [comment]
Having the same issue.

**Comment by hodlforjesus** [comment]
This has now been fixed with our new Carver2D Rev3 fork.
