### ISSUE TITLE
Only displaying a blank white screen on load

### ISSUE THREAD

**Issue by cpass78** [bulwark-crypto/bulwark-explorer#159]
## Expected Behavior
full ui displays at hostname/ip

## Actual Behavior
Blank white screen

## Steps to Reproduce the Problem
  1. yarn run build:web
  1. yarn run start:api

## Specifications
  - Version: master
  - Platform: Linux
  - Subsystem: Ubuntu 18.04 LTS

Api seems to be responding correctly however there are no ui elements being shown on the frontpage. The loading icon appears for a brief moment then the below error appears.

<img width="1420" alt="Screen Shot 2019-11-16 at 9 42 16 PM" src="https://user-images.githubusercontent.com/1406565/69002274-0f308a00-08ba-11ea-9b37-a54510c73a3c.png">

**Comment by waterfallm** [comment]
have you not run "yarn run start:web"

**Comment by cpass78** [comment]
Thats for running the dev server is it not? Im trying to run production

**Comment by cisnes** [comment]
+1. I'm in the same situation. Both web and api have been started with yarn

**Comment by cpass78** [comment]
Got the fix from @hodlforjesus. In config.js add `blockCountdowns:[] `anywhere in the config block. Fix should be pushed shortly
