### ISSUE TITLE
Masternode list isn't listing who has been paid, and is only listing various other transactions relating to Masternode addresses.

### ISSUE THREAD

**Issue by KaneoHunter** [bulwark-crypto/bulwark-explorer#39]
The masternode list isn't listing any transactions from coinbase.

The list is currently showing only non-coinbase transaction such as people depositing collateral.

http://explorer.bulwarkcrypto.com/#/masternode

Here is an example transaction which should be appearing on the list as a payment.

Status: 106 confirmations
Date: 22/03/2018 15:29
Source: Generated
Credit: 21.87500000 BWK
Net amount: +21.87500000 BWK
Transaction ID: 1c291153cd579b5cac68cff96d095f5a97da3f971227d3b3b727731289ca9061
Output index: 0

**Comment by dustinengle** [comment]
Can open at a later date as a feature update, closing for now.
