### ISSUE TITLE
Ram Error when looking up a wallet address.

### ISSUE THREAD

**Issue by KyleForDays** [bulwark-crypto/bulwark-explorer#45]
Discord User experienced a Ram error when searching for his address through the explorer. Error listed below.

Error: Executor error during find command: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.

User who experienced the issue is no longer around at this moment.

**Comment by dustinengle** [comment]
Does anyone have an example address I can use to verify/test with?  Thanks in advance.

**Comment by heguli97** [comment]
These ones caused me issues, i was the one who reported this bug on Discord.
bJ52wPsXbEbkKwgUXiN2BMf9nwFxYVCCSx
bHebxQEEoD46rtc9HDuifJC6uSbt3iAwyz

**Comment by dustinengle** [comment]
@heguli97 Awesome, thank you for posting.  We'll get this issue resolved right away.
