### ISSUE TITLE
Question to Block reward values

### ISSUE THREAD

**Issue by Caberhagen** [bulwark-crypto/bulwark-explorer#54]
## Expected Behavior
The sending value is lower then the recipients values together.

## Actual Behavior
It's not logic thats more payed as sent.?

## Steps to Reproduce the Problem

  1. to see on bulwark blockexplorer
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

![blvalues](https://user-images.githubusercontent.com/5205107/42677903-83b762ec-867d-11e8-8958-43ae84fd58e7.png)

**Comment by dustinengle** [comment]
That is a proof-of-stake(PoS) minted `stakebase` transaction.  The sending amount is the staker that won that block, and the receiving is the staked amount + plus share of reward with the second receiver being the masternode.
