### ISSUE TITLE
Address Balance not Reflected correct

### ISSUE THREAD

**Issue by Aviator-Coding** [bulwark-crypto/bulwark-explorer#71]
## Expected Behavior
If you check on https://explorer.bulwarkcrypto.com/#/address/bVDTm165kXnoB4rAJWGJ7scNXWyt1UXoxR

and see the wallet balance:
Sent:-33,453.5487 BWK
Received:+36,898.3604 BWK
Balance:3,444.8117 BWK

You will notice that this address has not sent any coins but it still shows as sent. The receive balance is off to it should be 3,444.8117 BWK. The Balance is correct.

I think the issue is in blockex.js Line 63 with related to this
const received = txs.reduce((acc, tx) => acc + tx.vout.reduce((a, t) => a + t.value, 0.0), 0.0);
and the query. I am trying to fix this on my fork as well but i thought i let you guys know as well. The Query will get all the Vouts listed not just the one with the address causes the math to be off.

Just ignore the Addresses here and focus on Vout you will see that both addresses are different but the explorer still adds these together causing the Balance to be off.

![image](https://user-images.githubusercontent.com/5182697/50294061-08e42480-0443-11e9-98e5-56f6233c6620.png)

## Actual Behavior 
Add just the Vouts with the current address so the send and received will match this would also then correct the send

## Steps to Reproduce the Problem

  1. goto https://explorer.bulwarkcrypto.com/#/address/bVDTm165kXnoB4rAJWGJ7scNXWyt1UXoxR
  2. check send and received (they will not match) the address has not send any coins
  3. check query 
 `db.txs.aggregate([
        { $match: { 'vout.address': 'bVDTm165kXnoB4rAJWGJ7scNXWyt1UXoxR' } },
        { $sort: { blockHeight: -1 } }
      ])
`
4. add vouts and see they doi not match
## Specifications
  - Version: Version which is live at explorer.bulwarkcrypto.com

**Comment by Aviator-Coding** [comment]
FYI: You could also gains some speed with that slow Query if you run them parallel instead of series.

this below reduce query time from 4198.916 ms to 1243.049 ms 
`    const txs_q1 = TX
      .aggregate([
        { $match: { 'vout.address': req.params.hash } },
        { $sort: { blockHeight: -1 } }
      ])
      .allowDiskUse(true)
      .exec();
    const utxo_q2 = UTXO
      .aggregate([
        { $match: { address: req.params.hash } },
        { $sort: { blockHeight: -1 } }
      ])
      .allowDiskUse(true)
      .exec();

    const txs = await txs_q1;
    const utxo = await utxo_q2;1

**Comment by Aviator-Coding** [comment]
I had some luck changing the Query. Would be cool if you guys can give a feedback if this fixes your issue as well.
```
.aggregate([
      {$match: { 'vout.address': req.params.hash } },
      {$project: {
      vout: {$filter: {
          input: '$vout',
          as: 'v',
          cond: {$eq: ['$$v.address', req.params.hash]}
      }},
      blockHash:1,
      blockHeight:1,
      createdAt:1,
      txId:1,
      version:1,
      vin:1,
    }},
    { $sort: { blockHeight: -1 } }
    ])
```
This will reflect the correct balance between send and receive

**Comment by dustinengle** [comment]
@Aviator-Coding Thanks the query works great, has been merged into master is live.
