### ISSUE TITLE
Previousblockhash not working (cron/block.js)

### ISSUE THREAD

**Issue by Aviator-Coding** [bulwark-crypto/bulwark-explorer#72]
## Expected Behavior
The cronjob the Previous Hash Field would be correct in the Database.blocks

## Actual Behavior
It does not Update Previous Hash Correct everything will be Genesis

![sync issues](https://user-images.githubusercontent.com/5182697/50358700-4078cc80-0528-11e9-8bc1-e5d2f5ef3ee1.PNG)

Line 
https://github.com/bulwark-crypto/bulwark-explorer/blob/master/cron/block.js#L41

needs to be 
```
prev: rpcblock.previousblockhash? rpcblock.previousblockhash: 'GENESIS',
```
i changed mine to:
```
prev: (rpcblock.height == 1) ? 'GENESIS' : (rpcblock.previousblockhash) ? rpcblock.previousblockhash : 'UNKNOWN',
```
Which will Be Unknown if not present past Block 1 or the Previous ID

As Seen Here:
![fixed](https://user-images.githubusercontent.com/5182697/50358877-cb59c700-0528-11e9-9ef5-7186817ae9db.PNG)

## Steps to Reproduce the Problem

  1.Run The Cron and Check the Database

## Specifications
  - Version: Current
  - Platform: Any

**Comment by dustinengle** [comment]
@Aviator-Coding Thanks again.
