### ISSUE TITLE
yarn run start:web / Explorer status "Offline"

### ISSUE THREAD

**Issue by ProjectHelixCoin** [bulwark-crypto/bulwark-explorer#77]
## Expected Behavior
Running `yarn run start:web` should start the explorer and have it connected to the daemon.

## Actual Behavior
Running  `yarn run start:web` 
![afbeelding](https://user-images.githubusercontent.com/42091981/50777497-10f1f000-129c-11e9-8f85-5b2260e5e3d6.png)

The explorer runs on localhost:8081, but the status stays on "Offline"
![afbeelding](https://user-images.githubusercontent.com/42091981/50777615-57474f00-129c-11e9-969d-344d93014368.png)

## Steps to Reproduce the Problem

  1. clone repo
  2. install deps
  3. edit config for mongo and rpc
  4. run script/cron_block.sh (which worked fine and got all the way to the last blocK)
  5. Run other cron commands:
```
yarn run cron:coin 
yarn run cron:masternode
yarn run cron:peer
yarn run cron:block
yarn run cron:rich
```
All worked fine and gave the "Done in x seconds" reponse.

 6. yarn run build:web
 7. yarn run start:web

Localhost:8081 lists the explorer, but the status stays "Offline"

## Specifications

  - Version: Github Master branch
  - Platform: Linux
  - Subsystem: Ubuntu 16.04

**Comment by dustinengle** [comment]
It looks like the `coin` cron is not running to completion.  The `Online` status is set in the coin cron here https://github.com/bulwark-crypto/bulwark-explorer/blob/master/cron/coin.js#L39.  

Look in the `./tmp` coin log file for errors or try running the script directly with node `node /path/to/blockex/cron/coin.js` and see if it prints anything.

**Comment by Aviator-Coding** [comment]
You need to start the api as well else it's not gonna work just to start the client.

**Comment by raisex** [comment]
ok guys, but for add host public instead localhost ?
i have tested in digitalocean vps but i don't see webpage

**Comment by Aviator-Coding** [comment]
replace localhost with server IP or use Nginx reserve Proxy.

**Comment by raisex** [comment]
@Aviator-Coding im agree with you but i not find web localhost ip where i can change. I see only rpc and api ip.

**Comment by Aviator-Coding** [comment]
```
api:{
     host:
}
```

**Comment by sotblad** [comment]
I'm having the exact same issue. Any idea on how I can fix it?

**Comment by hodlforjesus** [comment]
This was due to wrong config. Changing 443 for portworker(default) to 3000 fixed the issue.

Navigating to http://localhost:8081/ instead of http://localhost:3000/ solved the issue for @sotblad 

By looking at XHR in Chrome we noticed that /api/coin was going to http://localhost:8081 instead of http://localhost:3000
