### ISSUE TITLE
Explorer status "Offline"

### ISSUE THREAD

**Issue by smai2018** [bulwark-crypto/bulwark-explorer#86]
## Expected Behavior
Status: Online
Block, peers, CMC data are updated

## Actual Behavior
Status: Offline

## Steps to Reproduce the Problem

  1. clone repo
  2. install deps
  3. edit config for mongo and rpc
  4. run script/cron_block.sh (which worked fine and got all the way to the last block)

Run scripts:
yarn run cron:coin 
yarn run cron:masternode
yarn run cron:peer
yarn run cron:block
yarn run cron:rich
All worked fine and gave the "Done in x seconds" reponse.

yarn run build:web
yarn run start:api
yarn run start:web

Running without Nginx. Changed the api port to 80 in the config.js. Logfiles are empty, when I run the scripts with node ./cron/coin.js no output, it means exit 0.  

When I call the api http://mywebserver/api/coin/ I have a json output with "status":"Online" inside. 

What I'm doing wrong?

## Specifications

  - Version: master
  - Platform: Linux
  - Subsystem: Ubuntu 18.04 LTS

**Comment by smai2018** [comment]
Got it myself. 💯

**Comment by WlanWerner** [comment]
> 
> 
> Got it myself. 💯

If you read this cann you maybe tell us how because I have the same issue

**Comment by enekoastorkiza** [comment]
> Got it myself. 💯

How do you solved it ??? i have the same issue

**Comment by ghost** [comment]
> 
> 
> > Got it myself. 💯
> 
> How do you solved it ??? i have the same issue

I do not know what it was in the end anymore, but you should check if you set your api right aswell as the webserver configuration
