### ISSUE TITLE
Navigation Menu Suggestions

### ISSUE THREAD

**Issue by KaneoHunter** [bulwark-crypto/bulwark-explorer#9]
The bar on the left side could use some improvements in my opinion.

Firstly, please can there be a large box to select, instead of a text box - as on my 1st use it took a few clicks to get to actually change pages.

Additionally, can there be an animation of some form when you are hovering your mouse over something clickable.

Furthermore, is it possible that on the desktop version the navigation menu can expand on mouseover.

Finally, there is a large empty area at the bottom of the menu. I would love to see a summary of some important coin information there. e.g Price, MN count, Block Height, Difficulty,.

**Comment by padraiq** [comment]
Larger hover areas and active indicator are planned.

**Comment by dustinengle** [comment]
Indicators (arrow & title) and animation have been added.
